### ISSUE TITLE
Roboto Condensed Light not referencable on Windows

### ISSUE THREAD

**Issue by davidski** [hrbrmstr/hrbrthemes#10]
Under Windows 10 x64 Pro, installing the full set of Roboto Condensed styles (whether via `hrbrthemes::import_roboto_condensed()` or manual install and `extrafont::font_import`) will only register `Roboto Condensed` and not `Roboto Condensed Light`. This soft-breaks `theme_ipsum_rc` (warnings are generated and the relevant elements are not rendered correctly).

I believe this is due to style linking in the TTF files. Windows appears to be "helpfully" limiting the styles that are exposed (only the font family appears in other programs such as MS Word, etc.).

I've searched around and haven't found any resources on how to work around this. ☹️

**Comment by hrbrmstr** [comment]
ugh but thx. i actually ran winbuilder tests (it tests RC) and this didn't
show up will try to mitigate.

**Comment by alexwhan** [comment]
Nice timing - I just went to file the same issue... happy to help if you can point to resources

**Comment by hrbrmstr** [comment]
That @davidski is always trying to get me to run Windows. Many thanks for both of you pointing this out. I think I have to do a system test and change which font it uses accordingly.

**Comment by hrbrmstr** [comment]
Just pushed an update to 0.2.0 that _I think_ handles this (downgrades from light to just rob cond). No rush on testing. I've got a few wks before another CRAN run.

**Comment by hrbrmstr** [comment]
Moving the rest of this discussion to #12
