### ISSUE TITLE
Mismatch between supplied theme_ipsum_rc and sample graphs

### ISSUE THREAD

**Issue by davidski** [hrbrmstr/hrbrthemes#11]
The demo plots for `theme_ipsum_rc` both here and on your blog seem to be using a lighted `panel.grid` color value that what's at https://github.com/hrbrmstr/hrbrthemes/blob/master/R/roboto-condensed.r#L74-L76. On my test installs (yes, Windows 10 🤷‍♂️ ) it looks like the supplied color value should be `grey80` (or its moral equivalent).

Can you verify the current value of #2b2b2b99 is the desired default? Sample from my install included below for reference.

![heavy_lines](https://cloud.githubusercontent.com/assets/2313762/23485435/41a01492-fe90-11e6-8e02-1086405940be.png)

**Comment by hrbrmstr** [comment]
might be due to screen captures being from a retina monitor. will validate
tho.

**Comment by hrbrmstr** [comment]
`#cccccc` is the new default starting in 0.2.0 (just pushed said change and also parameterized this + axis colors).

**Comment by davidski** [comment]
Still defaults to #2b2b2b99 in `theme_ipsum_rc` via https://github.com/hrbrmstr/hrbrthemes/blob/master/R/roboto-condensed.r#L71, I'm afraid.
