### ISSUE TITLE
Registering fonts on windows

### ISSUE THREAD

**Issue by alexwhan** [hrbrmstr/hrbrthemes#12]
I am unable to use Roboto Condensed on windows unless I first attach the [extrafont package](https://github.com/wch/extrafont/blob/master/R/aaa.r), which you can see has some windows special sauce:

```
.onAttach <- function(libname, pkgname) {
    packageStartupMessage("Registering fonts with R")

    ## Load all fonts
    loadfonts("pdf", quiet = TRUE)
    loadfonts("postscript", quiet = TRUE)
    if (.Platform$OS.type == "windows") {
        loadfonts("win", quiet = TRUE)
    }
}
```

After loading extrafont, all works well

**Comment by hrbrmstr** [comment]
i have to noodle a bit on this one. generally, one has to do this (use extrafont to load fonts for PDF and PostScript) for any non-core font for those devices (they have no impact on bitmap devices like PNG and shld not have any bearing on the svglite device). For someone like myself with an insane amount of fonts on his system, I `loadfonts` introduces a very noticeable delay and i only do it for work projects that need PDF output (which is about 8x a year). 

if i added an option check (i.e. test for `hrbrloadfonts`) then that's an extra bit of code folks have to run anyway vs just use an extra line of code (or 2) to do the `loadfonts`. 

Perhaps @bhaskarvk & @davidski can toss some opines here regarding ^^l

**Comment by davidski** [comment]
Unfortunately, `loadfonts` is required to make fonts available even to the Windows bitmap device. Without attaching `extrafont`, `theme_ipsum_rc` will still fail to use the correct font and throw warnings on Windows.

I've also struggled with the "to load extrafont or not to load" question and and currently am doing an attachment in my code. My audience is far smaller and narrower, so simply documenting that `library(extrafont)` is required for Windows users may be a good choice for now.

**Comment by hrbrmstr** [comment]
O_o How anyone can still use Windows is beyond me :-) Thx for that
clarification, tho. Lemme see what I can whip up that causes the least
amount of "pain" for those of us with tons of fonts. That's a tiny fraction
of users, but it's multiple, noticeable, painful seconds :-)

**Comment by hrbrmstr** [comment]
the update I just made shld take care of this. I tried a compromise solution to both Windows and PDF/PS fonts. Win is autoloaded (since I'll _never_ have to deal with that :-) and i made a global pkg option for the PDF/PS load. Also added a font presence check on pkg startup.

**Comment by alexwhan** [comment]
working perfectly for me. (btw most of us blame our employers for the windows situation...)
thanks for such prompt attention to an issue that doesn't affect you!

**Comment by hrbrmstr** [comment]
thx for testing! I'll wait til the _other_ _voluntary_ Windows person *cough* @davidski *cough* tests it and close it after.

**Comment by davidski** [comment]
LGTM! 🚢 it!

**Comment by grepinsight** [comment]
I--Windows user -- ran into the same problem and found this thread, and it solved the problem beautifully!! Thanks Mr.Rudis for making this package!
