### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by Alison-Lukan** [hrbrmstr/hrbrthemes#47]
Install works fine, but when I try to add hrbrthemes to and get the following error:

`> library(hrbrthemes)
Error: package or namespace load failed for ‘hrbrthemes’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so
  Reason: image not found`

Any help would be appreciated.

**Comment by mulanrouge** [comment]
Hi, I have the same error. have you fixed that?

**Comment by MKnierim** [comment]
I had the same issue, was solved by:

"Installing XQuartz (and restarting)"

 As referenced here: https://github.com/hrbrmstr/hrbrthemes/issues/35
