### ISSUE TITLE
Gridlines and Axis Labels are Out of Alignment

### ISSUE THREAD

**Issue by SeabassHeyneman** [hrbrmstr/hrbrthemes#51]
Hi! I appreciate the work that went into this because it makes it much easier to put my analysis into a ready-state to share with stakeholders. I wanted to bump up this small nit.

It looks like the y-axis labels aren't in alignment with the y-axis gridlines.

Here's the code to generate these plots:

```
library(tidyverse)
library("hrbrthemes")

df <- data.frame(
  name = c("bookshelf", "coffee table", "snowglobe"),
  value = c(100, 28, 13)
)

df %>% 
  ggplot(aes(name, value)) +
  geom_col() +
  theme_ipsum_rc(grid = "y")
```

Here's the plots:

<img width="973" alt="Screen Shot 2020-04-15 at 10 27 04 PM" src="https://user-images.githubusercontent.com/52939487/79417943-42aa3a00-7f68-11ea-950b-e9b7bd43b0be.png">
<img width="970" alt="Screen Shot 2020-04-15 at 10 27 20 PM" src="https://user-images.githubusercontent.com/52939487/79417955-4938b180-7f68-11ea-9fce-27b52fba5a6a.png">

**Comment by hrbrmstr** [comment]
the help on `theme_ipsum_rc` (and all the themes in the pkg) states this definition for the `grid` parameter:

```
panel grid (TRUE, FALSE, or a combination of X, x, Y, y)
```

`X` and `Y` are for major grid, `x` and `y` are for minor grid

You're using lowercase, not uppercase.
