### ISSUE TITLE
theme_ipsun fonts not working

### ISSUE THREAD

**Issue by srgmld** [hrbrmstr/hrbrthemes#52]
I am not being able to apply extra fonts when using the theme_ispun fucntion (theme_ipsun_rc specifically).
Steps I have followed:
1. Dowonload and isntall fonts from google fonts (Roboto Condenced).
2. Import new fonts in Rstudio using extrafont::font_import( ) function.
3. Load new fonts in Rstudio using extrafont::loadfonts( ) function. As an alternative I used extrafont::loadfonts(device = "win") 
4. Apply the theme_ipsum_rc( ) function on a ggplot command

The theme_ipsun_rc( ) is working; however, the font is not being applied. There is no error or warning at any point.

Any suggestion about what else can I do?

**Comment by hrbrmstr** [comment]
I'll be moving the package over to using the fairly new {systemfonts} package (vs {extrafont}) which may help ease font pains.
