### ISSUE TITLE
Paris

### ISSUE THREAD

**Issue by zx8754** [hrbrmstr/hrbrthemes#6]
> **Kern-what?**
> 
> Kerning is nothing more than a fancy word for spaces between letters and fonts have built-in tables for how various paris of letters should be placed next to each other.

**Comment by hrbrmstr** [comment]
and…?

**Comment by zx8754** [comment]
Oops sorry was it meant to me paris or pairs?

**Comment by hrbrmstr** [comment]
ARGH!

sorry (totally did not grok what you were saying)

thx ;-) will here soon and post to CRAN in a month

**Comment by zx8754** [comment]
Phew, I thought you really meant Paris, and re-read it many times to trying to make sense :)

Thanks, I will close this issue.

Another thing, in case you didn't know, relevant to your website, the share button for Twitter just opens the same page in a new tab, instead of opening Twitter.

**Comment by hrbrmstr** [comment]
(thx for the note re: twitter thing)

Spelling fixed! #ty
