### ISSUE TITLE
Lighter color on grids

### ISSUE THREAD

**Issue by dmi3kno** [hrbrmstr/hrbrthemes#7]
Hi,
I have seen people use the hrbrthemes and immediately change the 
```
theme(panel.grid.major=element_line(color="#cccccc"))
theme(panel.grid.minor=element_line(color="#cccccc"))
```
or even lighter (#d9d9d9 or #e6e6e6). Last value is probably too light on print, but default 17% grey looks noisy, especially on things like geom_boxplot(). Have you considered lighter colors for grid?

**Comment by hrbrmstr** [comment]
Put it up for a broader vote 😀: https://twitter.com/hrbrmstr/status/836002855446261760

**Comment by dmi3kno** [comment]
Not sure your tweet was clear, but ok. I think the right answer may be more nuanced than simple change of color. The needs might vary from geom to geom (including no grid in some cases).

**Comment by ikashnitsky** [comment]
I came here to propose just the same. 
The `theme_ipsum_rc()` is amazing except for the too heavy grid.
I would be happy with a solution like 
`theme_ipsum_rc(grid = "light")`
where "light" matches the `panel.grid` parameters of `theme_minimal()`

**Comment by hrbrmstr** [comment]
aye. one does def need to consider the plot when deciding to use a grid and tweak the grid and not having a param shortcut for it is actually kind of annoying (I end up adding `theme()`s and that's a pain). Working on a potentially lighter default but def adding a parameter for grid and axis line color.
